### ISSUE TITLE
Vote with a hash of the bank state

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1131]
After the following are implemented:

- [x] #1129 Vote downstream from Bank updates
- [x] #1130 Hash the Bank state
- [x] #1200 Associate the Bank state hash with an Entry ID

change the `Vote` message to include a hash of the bank state and update the leader to reject any votes that don't match its own hash.

**Comment by garious** [comment]
@rob-solana you mentioned wanting to take this one from me earlier? Assign it to @carllin?

**Comment by rob-solana** [comment]
👍

**Comment by rob-solana** [comment]
vote at specific PoH tick counts, let's call 'em "voting rounds"

**Comment by rob-solana** [comment]
CC #1428

**Comment by garious** [comment]
@rob-solana, @carllin, what's the news here? I'm surprised to still assigned to Tabletops.

**Comment by garious** [comment]
Update: Instead of adding the hash to the `Vote` we can add it to the instruction that the leader sends to start a vote (possibly named `VoteInstruction::NewBlock`). Then the `Vote` instructions just need to be updated to target the account created by that instruction and send it from `ReplayStage` after verifying it reproduced the same hash.

**Comment by rob-solana** [comment]
cool

**Comment by garious** [comment]
Bumped to Grandview. Depends on BankForks and I'll be busy with book updates next week.

**Comment by sagar-solana** [comment]
@garious, did you have a design in mind for how to do this.
At what point should we intercept and de-serialize the vote? We do have a dedicated banking_stage thread for votes, perhaps that would be the place for this? (it might slow down vote processing a little)

**Comment by garious** [comment]
@sagar-solana There's no design document for this - just a goal: stop blindly accepting votes. A vote with an inconsistent state hash at a given slot height should be rejected.

**Comment by sagar-solana** [comment]
@garious, gotcha, does my proposal seem ok though?

> We do have a dedicated banking_stage thread for votes, perhaps that would be the place for this?

**Comment by garious** [comment]
@sagar-solana That makes sense to me, but a failing unit-test says 1000 words. :)

**Comment by mvines** [comment]
From #4401:
> Fixes #4246, #1131, #4245

Github syntax is wrong but clearly the intent there was to close this issue as fixed.
