### ISSUE TITLE
Unignore RUSTSEC-2020-0077 after 1.4.17 release

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#14084]
#### Problem

`solana-frozen-abi` and `solana-runtime` depend on the now abandoned `memmap` crate.  It has been replaced by the maintained `memmap2` fork in #14081, but we have some packages depending on the published 1.4.16 release crates, so still get flagged.

#### Proposed Solution

Revert ignore commits after 1.4.17

- [x] master - 1792100e2b4d474e97bfcb7bcb947cd213bb7bcc (#14170)
- [x] v1.5 - 1792100e2b4d474e97bfcb7bcb947cd213bb7bcc (#14171)
- [x] v1.4 - bd6cad3891a1b0d753ad87ef2c6923aaf34d380c (#14173)
- [x] ~v1.3 - 119815f2dadd14d5b6e43fb73033c66ac328a94c~ v1.3 is EOL
