### ISSUE TITLE
multinode demo

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#256]
- [x] at GPU speeds with 2 nodes I am seeing more window drops.  still to many retransmit asks.  I think the solution is to do a pipeline for this stage as well.  pull all the crdt requests from the socket.  reply to all of them, coalescing any duplicates.
 - [x] check single node perf again
- [x] seems to take forever to for the crdt to discover the other nodes.  need listener to use a streamer interface, and we should make the streamer threads high priority.  same issue as above. (#273)
- [x] get the demo working on sagan/newton (checkout the readme; try those IPs in the scripts #261 )
- [x] update readme (#261)
- [x] #254 merged
- [x] #258 merged.  this also changes event verify to call transaction verify plan
- [x] window repair backoff.  (the requests for a repair need control flow, they basically cause more packets to be sent, and duplicates, which cause more drops)
- [x] check single node perf, print tps out of the servers.  (fixed with bank sig verify bug, #261)
