### ISSUE TITLE
Prioritization Fee function enabling 

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#26017]
#### Problem

User should be able to land their transactions even when leaders are loaded or required write accounts are highly contended, if willing to bid for the access of the limited resources. 

This is a subset of #23211 to zoom in Priority Fee function rollout;

Project [Transaction Prioritization ](https://github.com/solana-labs/solana/projects/73) tracks tasks.

#### Proposed Solution
Allow users to pay prioritization_fee via `compute_budget` instruction. The transaction with highest prioritization_fee has highest priority to be considered by leader for block inclusion. 

`prioritization_fee` is defined as micro-lamport per compute-unit that user wants to pay for the transactions. For example, if a transaction's `compute_budget` instruction specifies priority_fee as 1,000 micro-lamports per cu, and requested_cu as 100,000 CUs, this transaction will be prioritized with `1,000` as priority-fee, and be charged for a `priority-fee` of (1,000 micro-lamport/cu * 100,000 cu = 0.1 lamport). The `priority-fee` will be accounted into transaction total-fee (alone with signature fee, write lock fee, compute fee). 

This schema encourages dev to request accurate CU (to lower total_fee), and allows users willing to pay to prioritize their transactions. 

#### V0 Rollout Progress

- [X] Rework banking stage to support prioritization of buffered packets, #24613

- [X] Banking stage prioritize transactions based on compute_budget instruction's `priority-fee`, not feature gated. #25178 in v1.10.15

- [X] Updated prioritization fee calculations for instructions that use the ComputeBudget::SetComputeUnitPrice instruction. #25178 in v1.10.15 (feature gated #25050)

- [x] To avoid forward queue being saturated by transactions to hot accounts, transactions should be forwarded by account bucket in priority order. #25406 

- [x] RPC supports user query for min priority_fee to land transactions in recent blocks, and min priority_fee to write to accounts. #26561

- [x] CLI supports use of priority-fee, #26464 

- [x] Update docs on how to use this function, #26014 

- [X] Create doc about the fee model as whole, #26615 

- [x] Active feature on testnet and devnet
    - [x] #25050

- [x] active feature on mainnet-beta
    - [x] #25050

#### V1 tasks:
- [ ] Add ability to filter transactions pre-sigverify when accounts hit write-compute limit, #24657

- [ ] High priority transactions should be retried more often, #26015 

- [ ] Add a transaction prioritization API to the JavaScript library (@solana/web3.js), #27607

**Comment by bluto658** [comment]
Why not alter the transaction model to not only take into account absolute compute, but also if the compute can be parallelized?

**Comment by steveluscher** [comment]
@taozhu-chicago, would you like to add a task for me here to add a transaction prioritization API to the JavaScript library (`@solana/web3.js`)?

**Comment by taozhu-chicago** [comment]
> @taozhu-chicago, would you like to add a task for me here to add a transaction prioritization API to the JavaScript library (`@solana/web3.js`)?

Added, issue #27607; It is also tracked in project https://github.com/solana-labs/solana/projects/73
