### ISSUE TITLE
Add market maker benchmark to test testnet cluster performance

### ISSUE THREAD

**Issue by KirillLykov** [solana-labs/solana#28925]
#### Problem

Current status: we test performance of the cluster using different bench programs such as bench-tps which are to test the cluster under specific load pattern, but we don't have bench programs to test more real-life scenarios.
Goal: introduce benchmarking scripts to test cluster behavior under different realistic loads. In particular, Market making on DEX.

#### Proposed Solution

For MM on dex, we are using [mango scripts index.ts and keeeper.ts](https://github.com/godmodegalactus/configure_mango) along with [solana-mango-bench](https://github.com/godmodegalactus/mango_bencher).

<img width="650" alt="Screenshot 2022-11-22 at 11 56 31" src="https://user-images.githubusercontent.com/687962/203296868-8aad4401-119b-4843-811a-5803b524db79.png">

The way it can be setup:

```bash
# BUILD MACHINE: build mango_bencher
if [[ ! -f "./mango_bencher" ]]
then
    git clone https://github.com/KirillLykov/mango_bencher.git
fi

cd mango_bencher
cargo build --release

# TODO(klykov1): copy `solana-mango-bencher` to the client machine

# KEEPER CLIENT MACHINE: install dependencies
# 1. install node.js: https://github.com/nodesource/distributions/blob/master/README.md
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs
# 2. install typescript and yarn
sudo npm install -g typescript
sudo npm install -g ts-node
sudo npm install -g yarn

# prepare keeper to run
git clone git@github.com:godmodegalactus/configure_mango.git
cd configure_mango
# probably not needed anymore
# npm install && yarn add @blockworks-foundation/mango-client

export CLUSTER=testnet 
export GROUP=testnet
export ENDPOINT_URL=http://api.testnet.rpcpool.com/
# Don't need to create accounts since they were already created once for testnet
# for private cluster, need to call `yarn ts-node index.ts`
scp remote/authority.json ./
# probably unnecessary
scp remote/accounts-50.json ./ 
scp remote/ids.json ./

# run keeper to have prices updated
export CONSUME_EVENTS_INTERVAL=100
export CONSUME_EVENTS_LIMIT=20
export UPDATE_CACHE_INTERVAL=1000 # def 3000
export UPDATE_ROOT_BANK_CACHE_INTERVAL=2000 # def 5000
# Important artifact: keeper.log
yarn ts-node keeper.ts > keeper.log 2> 1

# BENCH CLIENT MACHINE for tests: run client
NET_OR_IP=${CLUSTER} 
# Copy files 
scp remote/authority.json ./
scp remote/accounts-20_1.json ./ 
scp remote/ids.json ./
# Important artifact: tlog.csv, blog.csv
solana-bench-mango -- -u ${NET_OR_IP} --identity ../configure_mango/authority.json --accounts ./accounts-20.json  --mango ./ids.json --mango-cluster ${IP_OF_MANGO_CLIENT} --duration 120 -q 2 --transaction_save_file tlog.csv --block_data_save_file blog.csv  2> err.txt &
```

The next step:
1. Fix `indexer.ts` to use `CLUSTER` env instead of `localhost:8899`: https://github.com/godmodegalactus/configure_mango/pull/3
2. Introduce mango_bencher with all the setup scripts to the CI (with the helpf of @pieceofr)
3. Test the setup on testnet, tune parameters of the client if required
4. Optimize performance of the mango_bencher client itself (https://github.com/godmodegalactus/mango_bencher/issues/6)
5. Make these runs to be reproducible exactly by providing a time feed (https://github.com/godmodegalactus/mango_bencher/issues/5)
6. Get rid of git submodules in the client code https://github.com/godmodegalactus/mango_bencher/issues/4 (with the help of the client author)

**Comment by godmodegalactus** [comment]
Great I will fix all the issues that are cited over here so that we can integrate into solana.

**Comment by KirillLykov** [comment]
The way it can be setup:

```bash
# BUILD MACHINE: build mango_bencher
if [[ ! -f "./mango_bencher" ]]
then
    git clone https://github.com/KirillLykov/mango_bencher.git
fi

cd mango_bencher
cargo build --release

# TODO(klykov1): copy `solana-mango-bencher` to the client machine

# KEEPER CLIENT MACHINE: install dependencies
# 1. install node.js: https://github.com/nodesource/distributions/blob/master/README.md
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs
# 2. install typescript and yarn
sudo npm install -g typescript
sudo npm install -g ts-node
sudo npm install -g yarn

# prepare keeper to run
git clone git@github.com:godmodegalactus/configure_mango.git
cd configure_mango
# probably not needed anymore
# npm install && yarn add @blockworks-foundation/mango-client

export CLUSTER=testnet 
export GROUP=testnet
export ENDPOINT_URL=http://api.testnet.rpcpool.com/
# Don't need to create accounts since they were already created once for testnet
# for private cluster, need to call `yarn ts-node index.ts`
scp remote/authority.json ./
# probably unnecessary
scp remote/accounts-50.json ./ 
scp remote/ids.json ./

# run keeper to have prices updated
export CONSUME_EVENTS_INTERVAL=100
export CONSUME_EVENTS_LIMIT=20
export UPDATE_CACHE_INTERVAL=1000 # def 3000
export UPDATE_ROOT_BANK_CACHE_INTERVAL=2000 # def 5000
# Important artifact: keeper.log
yarn ts-node keeper.ts > keeper.log 2> 1

# BENCH CLIENT MACHINE for tests: run client
NET_OR_IP=${CLUSTER} 
# Copy files 
scp remote/authority.json ./
scp remote/accounts-20_1.json ./ 
scp remote/ids.json ./
# Important artifact: tlog.csv, blog.csv
solana-bench-mango -- -u ${NET_OR_IP} --identity ../configure_mango/authority.json --accounts ./accounts-20.json  --mango ./ids.json --mango-cluster ${IP_OF_MANGO_CLIENT} --duration 120 -q 2 --transaction_save_file tlog.csv --block_data_save_file blog.csv  2> err.txt &
```

**Comment by KirillLykov** [comment]
Checked on two different machines, the procedure works now.
The plan is the following:
1. Prepare scripts to run this procedure on automatic fashion
2. Run these scripts regularly
3. Add metrics to the mango_bencher to report them to InfluxDB
4. Try to get higher success rate by using different RPC strategy, use more than 1 client
5.

**Comment by KirillLykov** [comment]
This task was running on daily basis but after 1.14.12 update, all transactions are timing out. Investigating why

**Comment by KirillLykov** [comment]
Planned improvments:
~1. Create/run script which updates balance of clients from accounts.json file (https://github.com/godmodegalactus/configure_mango/pull/17#event-8373728268)~
2.  Test and update benchmarking scripts accordingly
3. Improve performance of the procedure by replacing keeper.ts with rust implementation
4. Add client identity when it will be added to bench-tps https://github.com/godmodegalactus/mango_bencher/issues/11
5. Add transaction fees to the client, like currently in [bench-tps](https://github.com/solana-labs/solana/blob/master/bench-tps/src/cli.rs#LL69C25-L69C25)

**Comment by KirillLykov** [comment]
New plans:
- [x] Publish influx metrics instead of just writing to logs (mango-bencher)
- [ ] Check that these metrics published as expected on testnet runs
- [ ] Update testnet scripts to reflect migration to the new repo, fork this repo to the solana org
- [ ] Update testnet scripts to use bencher without keeper, test that works (don't forget to specify authority by `keeper-authority`)
- [ ] Setup long runs with mango-bencher when the code is ready, don't forget to turn off transactions log because it might be too large
