### ISSUE TITLE
Sequence for testnet rehash fix

### ISSUE THREAD

**Issue by jeffwashington** [solana-labs/solana#28942]
#### Problem
Complex sequencing of a testnet fix #28934
- [x] test #28935 against testnet
- [x] review #28935 (@brooksprumo)
- [x] merge #28935 (anyone)
- [x] build a 1.14 release that should NOT be used for mnb or devnet (only testnet) but that includes #28935 (@willhickey)
version: 1.14.
- [x] update testnet to use the new 1.14 release with #28935
- [x] once enough is updated, activate the feature (@jeffwashington)
- [x] wait for epoch to changed and feature to be activated
- [x] build a 1.14 pr to revert 2/3 of #28935 to remove the effects of the temporary feature  (@jeffwashington) #28943
- [x] merge a 1.14 pr to revert 2/3 of #28935 to remove the effects of the temporary feature  (@jeffwashington) #28943
- [x] create a new release of 1.14 that IS now compatible again with mnb and devnet (and also testnet) that includes  #28943 (@willhickey)
- [x] test  new release with #28943 against testnet (and mainnet)
- [x] update all testnet to newer 1.14 whenever
- [x] merge the no-op feature into master (https://github.com/solana-labs/solana/pull/28936)  (@jeffwashington)
- [ ] activate the no-op feature on devnet and mnb whenever 1.15 is the minimum supported version on all networks (@jeffwashington)
