### ISSUE TITLE
Implement `getConfirmedBlock` RPC method

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#6867]
#### Problem
Solana users need a way to introspect particular blocks on the ledger via a request/response workflow. #6853 stubs out the initial methods. This ticket is to track remaining work.

#### Proposed Solution

Follow-up work:
- [x] Plumb methods into solana-web3.js (https://github.com/solana-labs/solana-web3.js/pull/552 & https://github.com/solana-labs/solana-web3.js/pull/555 & https://github.com/solana-labs/solana-web3.js/pull/562)
- [x] Add persistent Transaction-status store to rocksdb (#6958 )
- [x] Add transaction fee to persistent Transaction-status store (#6958 )
- [x] Write transaction statuses to rocksdb after `commit_transactions` (both leader and other validator) (#7030 )
- [x] Wrap transaction status write behind validator arg, to prevent rocksdb bloat on nodes that don't need/want this feature (#7030 )
- [x] Parse `get_slot_entries` from blocktree to return real data from `getConfirmedBlock` (#6966 )
- [x] Map Transaction-status to slot entries to flesh out `getConfirmedBlock` (#7011 )
- [x] Return blockhash and previous blockhash in `getConfirmedBlock` (#7004 )
- [x] Add parent slot to `getConfirmedBlock` (#7038 )
- [x] Flesh out unit tests in rpc.rs vis-a-vis real data (#7120 )
- [x] Update jsonrpc-api.md to document the new method (#7046 )

**Comment by mvines** [comment]
Can we call this done?

**Comment by CriesofCarrots** [comment]
> Can we call this done?

Almost. I'd still like a test in rpc.rs. I'll do that first thing and then close this.
