### ISSUE TITLE
Smart Contracts Engine Backend

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#953]
Smart Contracts Engine ideas are in #739.  That PR does to many things at once, so to make migration easier it will be broken up, and this issue will track the incremental changes.
1. [x]  #954 Accounts with state.  Accounts should have some user created state.  Transactions should be able to write to it.
2. [x] #979 Migrate Budget DSL to use the Account state instead of global bank data structures.  Serialize `Instruction` into `Transaction::user_data`.  Store the pending set in the `Account::user_data` Enforce the token balance rules on contract execution.  This becomes the entry point for generic contracts.
3. [x] #1189 Add `ContractId` to Accounts.  `system` contract interface that allows transactions to assign an `Account` to a `ContractId` as well as allocate memory.
4. [ ] Optimization: parallel execution of batches of transactions on multiple threads (in #739 this boosts perf from 300k to 500ktps in the engine)
5. [ ] Optimization: #950 
6. [ ] Loader that can upload an elf and add its entry point under a `ContractId`  (@jackcmay)

I would like @garious and @mvines to review the plan and comment

**Comment by garious** [comment]
Added 2 new issues under Pillbox for the remaining work
